AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  clinical-trial-parser

  Sample SAM Template for clinical-trial-parser

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  Stage:
    Type: String
    Default: Dev
    AllowedValues:
      - Prod
      - Dev
    Description: Set the deployment stage

Resources:
  ClinicalTrialParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /parser
            Method: POST
      Environment:
        Variables:
          VARIABLES_S3_URL:
            Fn::If:
              - IsProdStage
              - "https://kitsa-ctai-parser-resource.s3.amazonaws.com/variables-prod.csv"
              - "https://kitsa-ctai-parser-resource.s3.amazonaws.com/variables.csv"
          UNITS_S3_URL:
            Fn::If:
              - IsProdStage
              - "https://kitsa-ctai-parser-resource.s3.amazonaws.com/units-prod.csv"
              - "https://kitsa-ctai-parser-resource.s3.amazonaws.com/units.csv"

Outputs:
  ClinicalTrialParserAPI:
    Description: API Gateway endpoint URL for the Clinical Trial Parser
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/parser/"

  ClinicalTrialParserFunction:
    Description: Lambda Function ARN
    Value: !GetAtt ClinicalTrialParserFunction.Arn

  ClinicalTrialParserFunctionIamRole:
    Description: Implicit IAM Role created for ClinicalTrialParser function
    Value: !GetAtt ClinicalTrialParserFunctionRole.Arn

Conditions:
  IsProdStage: !Equals [!Ref Stage, 'Prod']
